version: '3.4'
services:
  tracker1: 
    image: jiuli//fastdfs-tracker
#    volumes:
#      - /home/fastdfs/tracker1/conf/fdfs_config:/etc/fdfs
    ports:
      - "22122:22122"
    
  tracker2:
    image: jiuli//fastdfs-tracker
#    volumes:
#      - /home/fastdfs/tracker2/conf/fdfs_config:/etc/fdfs
    ports:
      - "22123:22122"
  
  fastdht1:
    image: jiuli//fastdht
#    volumes:
#      - /home/fastdfs/fastdht1/conf/fdht_config:/etc/fdht
    
  fastdht2:
    image: jiuli//fastdht
#    volumes:
#      - /home/fastdfs/fastdht2/conf/fdht_config:/etc/fdht
    
  group1_storage1:
    image: jiuli//fastdfs-storage-dht
#    volumes:
#      - /home/fastdfs/group1-storage1/conf/fdht_config:/etc/fdht
#      - /home/fastdfs/group1-storage1/conf/fdfs_config:/etc/fdfs
#      - /home/fastdfs/group1-storage1/conf/nginx_config:/usr/local/openresy/nginx/conf
    #  - /home/fastdfs/group1-storage1/data:/home/jiuli/fastdfs/storage
    ports:
      - "23000:23000"
    links:
      - tracker1:tracker1
      - tracker2:tracker2
      - fastdht1:fastdht1
      - fastdht2:fastdht2
      
  group1_storage2:
    image: jiuli//fastdfs-storage-dht
#    volumes:
#      - /home/fastdfs/group1-storage2/conf/fdht_config:/etc/fdht
#      - /home/fastdfs/group1-storage2/conf/fdfs_config:/etc/fdfs
#      - /home/fastdfs/group1-storage2/conf/nginx_config:/usr/local/openresy/nginx/conf
    #  - /home/fastdfs/group1-storage2/data:/home/jiuli/fastdfs/storage
    ports:
      - "23001:23000"
    links:
      - tracker1:tracker1
      - tracker2:tracker2
      - fastdht1:fastdht1
      - fastdht2:fastdht2
      
#group2      
  fastdht3:
    image: jiuli//fastdht
#    volumes:
#      - /home/fastdfs/fastdht3/conf/fdht_config:/etc/fdht
    
  fastdht4:
    image: jiuli//fastdht
#    volumes:
#      - /home/fastdfs/fastdht4/conf/fdht_config:/etc/fdht
#    
  group2_storage1:
    image: jiuli//fastdfs-storage-dht
#    volumes:
#      - /home/fastdfs/group2-storage1/conf/fdht_config:/etc/fdht
#      - /home/fastdfs/group2-storage1/conf/fdfs_config:/etc/fdfs
#      - /home/fastdfs/group2-storage1/conf/nginx_config:/usr/local/openresy/nginx/conf
    #  - /home/fastdfs/group2-storage1/data:/home/jiuli/fastdfs/storage
    ports:
      - "23002:23000"
    links:
      - tracker1:tracker1
      - tracker2:tracker2
      - fastdht3:fastdht3
      - fastdht4:fastdht4
      
  group2_storage2:
    image: jiuli//fastdfs-storage-dht
#    volumes:
#      - /home/fastdfs/group2-storage2/conf/fdht_config:/etc/fdht
#      - /home/fastdfs/group2-storage2/conf/fdfs_config:/etc/fdfs
#      - /home/fastdfs/group2-storage2/conf/nginx_config:/usr/local/openresy/nginx/conf
    #  - /home/fastdfs/group2-storage2/data:/home/jiuli/fastdfs/storage
    ports:
      - "23003:23000"
    links:
      - tracker1:tracker1
      - tracker2:tracker2
      - fastdht3:fastdht3
      - fastdht4:fastdht4
      
  storage_proxy:
    image: jiuli//fastdfs-storage-proxy
#    volumes:
#      - /home/fastdfs/storage-proxy/conf/nginx_config:/usr/local/openresty/nginx/conf
    ports:
      - "8800:80"
    links:
      - group1_storage1:group1_storage1
      - group1_storage2:group1_storage2
      - group2_storage1:group2_storage1
      - group2_storage2:group2_storage2

      

# docker-compose up tracker1 tracker2 fastdht1 fastdht2 fastdht3 fastdht4 group1_storage1 group1_storage2 group2_storage1 group2_storage2 storage_proxy
# docker-compose stop tracker1 tracker2 fastdht1 fastdht2 fastdht3 fastdht4 group1_storage1 group1_storage2 group2_storage1 group2_storage2 storage_proxy
# docker-compose rm -f tracker1 tracker2 fastdht1 fastdht2 fastdht3 fastdht4 group1_storage1 group1_storage2 group2_storage1 group2_storage2 storage_proxy
      
# 如何加扩容，加组？
# 
